[project]
name = "digital-beaver-hunter"
version = "0.2.0"
description = "Beaver detection model suite using ultralytics"
authors = [
    { name = "initze", email = "ingmarnitze@gmail.com" }
]
dependencies = [
    "setuptools",
    "wheel",
    # "numpy",
    "opencv-python",
    "Pillow",
    "pyyaml",
    "requests",
    # "scipy",
    # "tqdm",
    "joblib>=1.4.2",
    "geopandas>=1.0.1",
    "leafmap>=0.42.11",
    "rasterio>=1.4.3",
    "typer>=0.15.1",
    "ipykernel>=6.29.5",
    "jupyterlab>=4.3.5",
    "typer-config>=1.4.2",
    # "wandb",
    "geoparquet-io>=1.1.1",
    "polars>=1.40.1",
    "folium>=0.19.4",
    "mapclassify>=2.10.0",
    "ultralytics[extra]>=8.4.51",
    # "ray[tune]>=2.55.1",
    # "optuna>=4.8.0",
    "torch>=2.10.0",
    "nvidia-nccl-cu12>=2.27.5",
    "ruff>=0.15.13",
    "wandb>=0.27.0",
    "tqdm>=4.67.3",
    "numpy>=2.4.6",
]
readme = "README.md"
requires-python = ">= 3.11"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.rye]
managed = true
dev-dependencies = []

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.targets.wheel]
packages = ["src/digital_beaver_hunter"]

[project.scripts]
dbh_inference = "digital_beaver_hunter.scripts.inference:app"
